#ifndef _ERRORCODES_H_
#define _ERRORCODES_H_

enum ERROR_CODES
{
  SUCCESS_NO_ERROR,
  ERROR_INIFILE_OPEN_FAILED,
  ERROR_INIFILE_READ_FAILED,
  ERROR_DB_CONNECTION_FAILED,
  ERROR_LOGFILE_OPEN_FAILED,
};

typedef int ERROR_CODE;


#endif
